#!/usr/bin/env bash
# Behavior tests for the kiro agent config generated by fm-spawn.sh.
#
# Exercises the tools grant, no-mistakes procedure delivery, and
# absent-optional-input degradation through real spawns with a fake tmux
# and a real isolated git worktree.
set -u

# shellcheck source=tests/fixtures.sh
. "$(dirname "${BASH_SOURCE[0]}")/fixtures.sh"

TMP_ROOT=$(fm_test_tmproot fm-spawn-kiro-config)

make_spawn_fakebin() {
  local dir=$1 fakebin
  fakebin=$(fm_test_make_spawn_fakebin "$dir")
  cat > "$fakebin/timeout" <<'SH'
#!/usr/bin/env bash
shift
exec "$@"
SH
  chmod +x "$fakebin/timeout"
  cat > "$fakebin/kiro-cli" <<'SH'
#!/usr/bin/env bash
exit 0
SH
  chmod +x "$fakebin/kiro-cli"
  printf '%s\n' "$fakebin"
}

make_spawn_case() {
  local name=$1 case_dir home proj wt fakebin launchlog id
  shift
  case_dir="$TMP_ROOT/$name"
  home="$case_dir/home"
  proj="$case_dir/project"
  wt="$case_dir/wt"
  launchlog="$case_dir/launch.log"
  fakebin=$(make_spawn_fakebin "$case_dir/fake")
  fm_test_spawn_home "$home" kiro
  fm_git_worktree "$proj" "$wt" "wt-$name"
  for id in "$@"; do
    fm_test_spawn_brief "$home" "$id"
  done
  printf '%s\n' "$case_dir|$home|$proj|$wt|$fakebin|$launchlog"
}

read_case_record() {
  # shellcheck disable=SC2034  # CASE_DIR is part of the shared record format
  IFS='|' read -r CASE_DIR HOME_DIR PROJ_DIR WT_DIR FAKEBIN_DIR LAUNCH_LOG <<EOF
$1
EOF
}

run_spawn() {
  local home=$1 wt=$2 fakebin=$3 launchlog=$4
  shift 4
  : > "$launchlog"
  FM_FAKE_LAUNCH_LOG="$launchlog" \
    fm_test_run_spawn "$home" "$wt" "$fakebin" "$@"
}

make_brief_with_mode() {
  local home=$1 id=$2 mode=$3
  mkdir -p "$home/data/$id"
  cat > "$home/data/$id/brief.md" <<EOF
# Task
{TASK}

# Definition of done
Delivery contract: mode=$mode
Brief text for $id
EOF
}

assert_valid_json() {
  local file=$1 label=$2
  python3 -c 'import json,sys; json.load(open(sys.argv[1]))' "$file" 2>/dev/null \
    || fail "$label: generated agent config is not valid JSON"
}

make_nm_fakebin() {
  local fakebin=$1
  cat > "$fakebin/no-mistakes" <<'SH'
#!/usr/bin/env bash
case "$*" in
  "axi run --help")
    printf '%s\n' '--intent is required when starting a new run' \
      '--yes auto-resolves every gate' \
      '--skip comma-separated pipeline steps to skip'
    exit 0 ;;
  "axi respond --help")
    printf '%s\n' '--action approve|fix|skip (required)' \
      '--findings comma-separated finding IDs to fix' \
      '--instructions guidance for selected findings'
    exit 0 ;;
  *) exit 0 ;;
esac
SH
  chmod +x "$fakebin/no-mistakes"
}

# Every kiro agent config must include "tools": ["*"] regardless of delivery
# mode. Without it, kiro-cli 2.18.0 grants zero tools and the worker cannot
# read, write, or run shell commands.
test_tools_grant_present_in_every_mode() {
  local mode id rec out status agent_config
  for mode in no-mistakes direct-PR local-only; do
    id="kiro-tools-${mode}"
    rec=$(make_spawn_case "tools-${mode}" "$id")
    read_case_record "$rec"
    make_brief_with_mode "$HOME_DIR" "$id" "$mode"
    make_nm_fakebin "$FAKEBIN_DIR"
    out=$(run_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" "$id" "$PROJ_DIR" --mode "$mode" --yolo off 2>&1)
    status=$?
    expect_code 0 "$status" "kiro spawn --mode $mode should succeed"
    agent_config="$WT_DIR/.kiro/agents/fm-${id}.json"
    assert_present "$agent_config" "$mode: kiro agent config was not generated"
    assert_valid_json "$agent_config" "$mode"
    assert_grep '"tools": ["*"]' "$agent_config" "$mode: kiro agent config missing tools grant"
  done
  pass "kiro agent config includes tools grant and valid JSON in every delivery mode"
}

# A no-mistakes kiro spawn generates a procedure file from no-mistakes axi
# help and points the agent config prompt at it via file:// URI.
test_nomistakes_procedure_delivered_to_kiro() {
  local id=kiro-nm-procedure rec out status agent_config procedure_file
  rec=$(make_spawn_case nm-procedure "$id")
  read_case_record "$rec"
  make_brief_with_mode "$HOME_DIR" "$id" no-mistakes
  make_nm_fakebin "$FAKEBIN_DIR"
  out=$(run_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" "$id" "$PROJ_DIR" --mode no-mistakes --yolo off 2>&1)
  status=$?
  expect_code 0 "$status" "kiro no-mistakes spawn should succeed"
  agent_config="$WT_DIR/.kiro/agents/fm-${id}.json"
  assert_present "$agent_config" "kiro agent config was not generated"
  assert_valid_json "$agent_config" "no-mistakes"
  assert_grep "file://fm-${id}-nm-procedure.md" "$agent_config" \
    "kiro agent config prompt does not point to the procedure file via file:// URI"
  procedure_file="$WT_DIR/.kiro/agents/fm-${id}-nm-procedure.md"
  assert_present "$procedure_file" "no-mistakes procedure file was not generated"
  assert_grep "no-mistakes axi" "$procedure_file" \
    "procedure file does not mention no-mistakes axi"
  assert_grep "--intent is required" "$procedure_file" \
    "procedure file does not contain run help output"
  assert_grep "--action approve" "$procedure_file" \
    "procedure file does not contain respond help output"
  pass "kiro no-mistakes spawn generates a procedure file referenced by the agent config"
}

# A direct-PR or local-only kiro spawn must NOT generate a procedure file.
# The prompt stays a static string.
test_non_nomistakes_kiro_has_no_procedure() {
  local mode id rec out status agent_config procedure_glob
  for mode in direct-PR local-only; do
    id="kiro-no-proc-${mode}"
    rec=$(make_spawn_case "no-proc-${mode}" "$id")
    read_case_record "$rec"
    make_brief_with_mode "$HOME_DIR" "$id" "$mode"
    make_nm_fakebin "$FAKEBIN_DIR"
    out=$(run_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" "$id" "$PROJ_DIR" --mode "$mode" --yolo off 2>&1)
    status=$?
    expect_code 0 "$status" "kiro spawn --mode $mode should succeed"
    agent_config="$WT_DIR/.kiro/agents/fm-${id}.json"
    assert_present "$agent_config" "$mode: kiro agent config was not generated"
    assert_valid_json "$agent_config" "$mode"
    assert_no_grep "file://" "$agent_config" \
      "$mode: kiro agent config should not use a file:// prompt"
    assert_grep "Follow your instructions exactly" "$agent_config" \
      "$mode: kiro agent config should use the static prompt"
    procedure_glob=$(find "$WT_DIR/.kiro/agents/" -name "*-nm-procedure.md" 2>/dev/null)
    [ -z "$procedure_glob" ] \
      || fail "$mode: kiro spawn generated a procedure file when it should not have"
  done
  pass "non-no-mistakes kiro spawns use a static prompt with no procedure file"
}

# When no-mistakes is absent from PATH, the kiro no-mistakes spawn must still
# succeed with no warning and no procedure file - the brief's DOD text still
# carries the contract.
test_absent_nomistakes_degrades_silently() {
  local id=kiro-nm-absent rec out status agent_config
  rec=$(make_spawn_case nm-absent "$id")
  read_case_record "$rec"
  make_brief_with_mode "$HOME_DIR" "$id" no-mistakes
  # Shadow no-mistakes with a stub that fails on axi help, simulating the
  # binary being absent or broken. fm_test_run_spawn prepends FAKEBIN to PATH
  # so this stub wins over the real binary.
  cat > "$FAKEBIN_DIR/no-mistakes" <<'SH'
#!/usr/bin/env bash
exit 1
SH
  chmod +x "$FAKEBIN_DIR/no-mistakes"
  out=$(run_spawn "$HOME_DIR" "$WT_DIR" "$FAKEBIN_DIR" "$LAUNCH_LOG" "$id" "$PROJ_DIR" --mode no-mistakes --yolo off 2>&1)
  status=$?
  expect_code 0 "$status" "kiro no-mistakes spawn without no-mistakes binary should succeed"
  agent_config="$WT_DIR/.kiro/agents/fm-${id}.json"
  assert_present "$agent_config" "kiro agent config was not generated"
  assert_valid_json "$agent_config" "absent no-mistakes"
  assert_grep '"tools": ["*"]' "$agent_config" \
    "absent no-mistakes: kiro agent config missing tools grant"
  assert_no_grep "file://" "$agent_config" \
    "absent no-mistakes: kiro agent config should not use a file:// prompt"
  assert_grep "Follow your instructions exactly" "$agent_config" \
    "absent no-mistakes: kiro agent config should fall back to the static prompt"
  printf '%s\n' "$out" | grep -qi 'warning\|error' \
    && fail "absent no-mistakes: spawn produced a warning or error"
  pass "absent no-mistakes binary degrades silently with a valid kiro agent config"
}

# The reworded brief must keep the contract line and all required rules.
test_reworded_brief_preserves_contract() {
  local home id brief
  home="$TMP_ROOT/brief-contract"
  mkdir -p "$home/data"
  id="brief-contract-z1"
  FM_HOME="$home" "$ROOT/bin/fm-brief.sh" "$id" some-proj --mode no-mistakes >/dev/null 2>&1
  brief="$home/data/$id/brief.md"
  assert_present "$brief" "brief was not scaffolded"
  grep -qx "Delivery contract: mode=no-mistakes" "$brief" \
    || fail "brief lost the byte-identical delivery contract line"
  assert_grep "Firstmate will then instruct you to start the no-mistakes validation pipeline" "$brief" \
    "brief lost the harness-neutral validation instruction"
  assert_no_grep "/no-mistakes" "$brief" \
    "brief still references the Claude-specific /no-mistakes slash command"
  assert_grep "You drive no-mistakes by responding to its gates, not by implementing fixes" "$brief" \
    "brief lost the gate-response rule"
  # shellcheck disable=SC2016
  assert_grep '`no-mistakes axi run --help`' "$brief" \
    "brief lost the axi run help reference"
  assert_grep "Do not hand-edit, commit, or fix findings yourself while a run is active" "$brief" \
    "brief lost the no-hand-edit rule"
  assert_grep "ask-user findings are never yours to answer" "$brief" \
    "brief lost the ask-user escalation rule"
  assert_grep "NEVER pass \`--yes\`" "$brief" \
    "brief lost the --yes ban"
  assert_grep "make \`--intent\` preserve all relevant content" "$brief" \
    "brief lost the --intent contract"
  assert_grep "done: PR {url} checks green" "$brief" \
    "brief lost the CI-green return point"
  pass "reworded no-mistakes brief preserves the contract line and every required rule"
}

test_tools_grant_present_in_every_mode
test_nomistakes_procedure_delivered_to_kiro
test_non_nomistakes_kiro_has_no_procedure
test_absent_nomistakes_degrades_silently
test_reworded_brief_preserves_contract
